server:
  port: 8080
  servlet:
    context-path: /api/@api.version@

game:
  port: 2000
  players: 4
players:
  min: 2
  max: 4
spring:
    datasource:
      url: jdbc:postgresql://ec2-34-247-72-29.eu-west-1.compute.amazonaws.com:5432/dd2av7eqokg7cn
      username: ttgrptavimafvd
      password: cc9cf5b3cc69dd214e18cc1410a23ce5edddeab100e4ffb86096bcc84fd4b8c9
      driver-class-name: org.postgresql.Driver
    jpa:
      properties.hibernate:
        show_sql: true
        format_sql: true
